build:
  maxIssues: 100

complexity:
  LongMethod:
    threshold: 40
  LongParameterList:
    functionThreshold: 5
  TooManyFunctions:
    thresholdInClasses: 11

naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    variablePattern: '[a-z][a-zA-Z0-9]*'

style:
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '10', '100', '1000']
  WildcardImport:
    active: true

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
